# Docs: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clo835-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clo835-app
  template:
    metadata:
      labels:
        app: clo835-app
    spec:
      containers:
        - name: clo835-app
          image: omoric01/clo835-a2:0.2
          ports:
            - containerPort: 8080
